#!/bin/bash
#
#############################################################
#                                                           #
#             WPSD Self-Signed SSL Cert. Gen.               #
#                                                           #
#############################################################
#
if [ "$(id -u)" != "0" ]; then
	echo -e "You need to be root to run this command...\n"
	exit 1
fi

source /usr/local/sbin/.wpsd-common-funcs

if [ "${OS_VER}" -lt 13 ]; then # only trixie and above
    echo "Unsupported WPSD release. To use this SSL helper script,"
    echo "you must be running WPSD Trixie (v.13) or greater."
    exit 1
fi

exec 200>/var/lock/wpsd-ssl.lock || exit 1
if ! flock -n 200 ; then
	echo -e "Another instance is already running...\n"
	exit 1
fi

# Option to force re-generaton, cert only lives for 1 year
if [ "$1" == "deletecert" ]; then
	rm -rf /etc/ssl/certs/wpsd.crt
	echo -e "SSL certificate deleted. Run this command again with the \"enable\""
	echo -e "option to generate a new certificate if you want to use https."

# Return to non-ssl state
elif [ "$1" == "disable" ]; then
	cd /etc/nginx/sites-enabled
	rm wpsd
	ln -s ../sites-available/wpsd wpsd
	# Restart NginX with the new config.
	systemctl restart nginx
	echo -e "SSL disabled. You will need to refresh the WPSD dashboard."

# Return to non-ssl state
elif [ "$1" == "enable" ]; then
	# If the self-signed cert doesnt exist - create it.
	if [ ! -f /etc/ssl/certs/wpsd.crt ]; then
		getFQDN=$( hostname -A | cut -d " " -f1 )
		# Create the new Private / Public keys
		openssl req -x509 -nodes -days 3650 -newkey rsa:4096 -keyout /etc/ssl/private/wpsd.key -out /etc/ssl/certs/wpsd.crt \
		  -subj "/C=US/ST=Minnesota/L=Winona/O=WPSD Project/OU=WPSD Dev Team/CN=wpsd" \
		  -addext "subjectAltName=DNS:wpsd,DNS:wpsd.local,DNS:pi-star,DNS:pi-star.local,DNS:pi-star*,DNS:pi-star*.local,DNS:${getFQDN},DNS:$(hostname).local,DNS:$(hostname)"
	fi
	# Configure NginX
	cd /etc/nginx/sites-enabled
	rm wpsd
	ln -s ../sites-available/wpsd-ssl wpsd
	# Restart NginX with the new config.
	systemctl restart nginx
	echo -e "SSL enabled. You will need to refresh the WPSD dashboard and "
	echo -e "add/accept the new self-signed certificate to your web browser."
else
	cat << EOF

WPSD Self-Signed SSL Manager

Description:
  This script manages the self-signed SSL certificate for the WPSD dashboard
  and toggles HTTPS support in the Nginx web server.

Usage:
  sudo wpsd-gensslcert [OPTION]

Options:
  enable      Generates a new certificate (if one does not exist) and
              configures the web server to use HTTPS.

  disable     Disables HTTPS and reverts the web server to standard HTTP.
              Note: This does *not* delete the existing certificate file.

  deletecert  Deletes the existing SSL certificate file.
              Note: If you are currently using HTTPS, you must run the
              "enable" command again immediately to generate a new key.

Important Notes:
  * This script must be run as root or via sudo.
  * Running "enable" or "disable" will restart the Nginx web server,
    making the dashboard temporarily unavailable.

EOF
fi
